[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=node_modules/@openzeppelin/"]
fs_permissions = [
    { access = "read", path = "./images/" },
    { access = "read", path = "./broadcast" },
]
ffi = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
